openapi: 3.0.0
info:
  description: Api Documentation
  version: "1.0"
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: expense-export-controller-v2
    description: Get and post expense or invoice export information.
  - name: expense-export-controller-v1
    description: Get and post expense export information.
paths:
  /v1/export-status:
    post:
      tags:
        - expense-export-controller-v1
      summary: Post status of an expense export.
      description: This web service allows an external application to post status of
        an expense export.
      operationId: updateExpenseExportStatusUsingPOST
      parameters:
        - name: chain-id
          in: header
          description: Used for tracking the flow of the request
          required: false
          schema:
            type: string
        - name: customer-code
          in: header
          description: Unique customer identifier provided by Chrome River
          required: true
          schema:
            type: string
        - name: export-id
          in: header
          description: Unique identifier for exported expense report
          required: true
          schema:
            type: string
        - name: x-api-key
          in: header
          description: API key for Authentication
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/ExportStatusModel"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Customer Code is missing.
        "401":
          description: Customer Code is not authorized. Cannot get expense export IDs.
        "404":
          description: Expense Report export file not found for the specified exportId.
        "409":
          description: Conflict.
        "422":
          description: UnprocessableEntity
        "503":
          description: Service unavailable. Please try again later.
      deprecated: false
  /v1/export-status/re-post:
    patch:
      tags:
        - expense-export-controller-v1
      summary: Repost External Export Status By ExportIds.
      description: This web service allows an external application to repost External
        Export Status By ExportIds.
      operationId: repostExternalExportStatusByExportIdsUsingPATCH
      parameters:
        - name: chain-id
          in: header
          description: Used for tracking the flow of the request
          required: true
          schema:
            type: string
        - name: context
          in: query
          description: The context of the export (e.g. invoice, expense)
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum:
              - expense
              - invoice
        - name: customer-code
          in: header
          description: Unique customer identifier provided by Chrome River
          required: true
          schema:
            type: string
        - name: x-api-key
          in: header
          description: API key for Authentication
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/repostExternalExportStatusByExportIdsUsingPAT\
          CHListOfExportids"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
        "404":
          description: Resource not found for exportId.
        "422":
          description: UnprocessableEntity
        "503":
          description: Service unavailable.
      deprecated: false
  /v1/exports:
    get:
      tags:
        - expense-export-controller-v1
      summary: Retrieve either a list of incoming expense export IDs or export details
        for a specific expense export.
      description: This web service allows an external application to fetch either a
        list of incoming expense export IDs or fetch export details for a
        specific export. To retrieve the list of export IDs, no export-id should
        be passed in the header of this call. To retrieve details of a specific
        export, the export-id header should be populated with the desired export
        ID.
      operationId: getExportIdsUsingGET
      parameters:
        - name: chain-id
          in: header
          description: Used for tracking the flow of the request
          required: false
          schema:
            type: string
        - name: customer-code
          in: header
          description: Unique customer identifier provided by Chrome River
          required: true
          schema:
            type: string
        - name: present
          in: query
          required: false
          schema:
            type: boolean
        - name: x-api-key
          in: header
          description: API key for Authentication
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExportIdsModel"
        "400":
          description: Customer Code is missing.
        "401":
          description: Customer Code is not authorized. Cannot get expense export IDs.
        "404":
          description: Expense Report export file not found for the specified exportId.
        "503":
          description: Service unavailable. Please try again later.
      deprecated: false
  /v2/export-status:
    post:
      tags:
        - expense-export-controller-v2
      summary: Post status of an expense or invoice export.
      description: This web service allows an external application to post status of
        an expense or invoice export.
      operationId: updateExportStatusUsingPOST
      parameters:
        - name: chain-id
          in: header
          description: Used for tracking the flow of the request
          required: false
          schema:
            type: string
        - name: context
          in: header
          description: The context of the export (e.g. invoice, expense)
          required: true
          schema:
            type: string
            enum:
              - expense
              - invoice
        - name: customer-code
          in: header
          description: Unique customer identifier provided by Chrome River
          required: true
          schema:
            type: string
        - name: export-id
          in: header
          description: The ID of the export file to update status of
          required: true
          schema:
            type: string
        - name: x-api-key
          in: header
          description: API key for Authentication
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/ExportStatusModel"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Customer Code is missing.
        "401":
          description: Customer Code is not authorized. Cannot get expense export IDs.
        "404":
          description: Expense Report export file not found for the specified exportId.
        "409":
          description: Conflict.
        "422":
          description: UnprocessableEntity
        "503":
          description: Service unavailable. Please try again later.
      deprecated: false
  /v2/export-status/re-post:
    patch:
      tags:
        - expense-export-controller-v2
      summary: Repost External Expense Export Status By ExportIds.
      description: This web service allows an external application to repost External
        Expense Export Status By ExportIds.
      operationId: repostExternalExportStatusByExportIdsUsingPATCH_1
      parameters:
        - name: chain-id
          in: header
          description: Used for tracking the flow of the request
          required: true
          schema:
            type: string
        - name: context
          in: query
          description: The context of the export (e.g. invoice, expense)
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum:
              - expense
              - invoice
        - name: customer-code
          in: header
          description: Unique customer identifier provided by Chrome River
          required: true
          schema:
            type: string
        - name: x-api-key
          in: header
          description: API key for Authentication
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/repostExternalExportStatusByExportIdsUsingPAT\
          CHListOfExportids"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
        "404":
          description: Resource not found for exportId.
        "422":
          description: UnprocessableEntity
        "503":
          description: Service unavailable.
      deprecated: false
  /v2/exports:
    get:
      tags:
        - expense-export-controller-v2
      summary: Retrieve either a list of incoming expense/invoice export IDs or export
        details for a specific export.
      description: This web service allows an external application to fetch either a
        list of incoming expense/invoice export IDs or fetch export details. To
        retrieve the list of export IDs, no export-id should be passed in the
        header of this call. To retrieve details of a specific export, the
        export-id header should be populated with the desired export ID.
      operationId: getExportIdsUsingGET_1
      parameters:
        - name: chain-id
          in: header
          description: Used for tracking the flow of the request
          required: false
          schema:
            type: string
        - name: context
          in: header
          description: The context of the export (e.g. invoice, expense)
          required: true
          schema:
            type: string
            enum:
              - expense
              - invoice
        - name: customer-code
          in: header
          description: Unique customer identifier provided by Chrome River
          required: true
          schema:
            type: string
        - name: export-id
          in: header
          description: The ID of the export file
          required: false
          schema:
            type: string
        - name: x-api-key
          in: header
          description: API key for Authentication
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExportIdsModel"
        "400":
          description: Customer Code is missing.
        "401":
          description: Customer Code is not authorized. Cannot get expense export IDs.
        "404":
          description: Expense Report export file not found for the specified exportId.
        "503":
          description: Service unavailable. Please try again later.
      deprecated: false
servers:
  - url: https://service.chromeriver.com
components:
  requestBodies:
    repostExternalExportStatusByExportIdsUsingPATCHListOfExportids:
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
      description: exportIds
      required: true
    ExportStatusModel:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ExportStatusModel"
      description: Payload required to post status of an export
      required: true
  schemas:
    ExportIdsModel:
      type: object
      required:
        - exportIds
      properties:
        exportIds:
          type: array
          example:
            - 5F98D1D2-B67E-DDC5-EF62-2237531E8ADB
          description: List of export IDs.
          items:
            type: string
      title: ExportIdsModel
    ExportStatusModel:
      type: object
      required:
        - status
      properties:
        code:
          type: string
          example: SAP_G200
          description: Arbitrary success/error code (optional). Max 50 characters.
        description:
          type: string
          example: File exportId.xml has been successfully exported
          description: Description (optional). Max 250 characters.
        sendEmail:
          type: boolean
          example: true
          description: "Send an accounting sync email notification for errors. SendEmail
            (optional) is a boolean: [true | false]"
        status:
          type: string
          example: success
          description: Status of an expense export.
          enum:
            - success
            - error
            - transferred
      title: ExportStatusModel
